name: omdb_movies_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  google_sign_in: ^5.4.2
  freezed_annotation: ^2.2.0
  dio: ^4.0.6
  cloud_firestore: ^4.0.2
  uuid: ^3.0.6
  async: ^2.9.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
