// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb_u1wdLkh9Tm-gOpGZ0JCNy-87OqHBQI',
    appId: '1:967940242977:android:2af9edafa55cac149aad60',
    messagingSenderId: '967940242977',
    projectId: 'fasal-omdb',
    storageBucket: 'fasal-omdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCELmb8PE6oPzuuWdoA0nOD0mCBMHxi6fE',
    appId: '1:967940242977:ios:0ed7a25f64b7e51b9aad60',
    messagingSenderId: '967940242977',
    projectId: 'fasal-omdb',
    storageBucket: 'fasal-omdb.appspot.com',
    androidClientId: '967940242977-ck6g8bknic6ije0to79hr3opo84m3vr9.apps.googleusercontent.com',
    iosClientId: '967940242977-k24fhiiqpare40shhhggdug4btoc4e1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.omdbMoviesApp',
  );
}
